// Data peserta undian Internet Merdeka — statis, tanpa database
// Struktur: { AGEN: { AREA: [nama, ...], ... }, ... }
// WAJIB_ZONK: warga yang WAJIB mendapat ZONK saat spin (tidak dapat hadiah)
const WAJIB_ZONK = {
  "ALDIN": {
    "LIABUKU": ["RIO", "YAYU", "HANS", "MERI"],
    "KOLESE": ["FANIZA"]
  },
  "MUNIR": {
    "KARYA BARU, BUGI, KAISABU": ["DEDE", "NURDIN", "WAHYU", "IMA", "RIO", "FARID", "ATI", "MULIADI", "WAHID"],
    "WABOROBO": ["RIAN"]
  },
  "NASRUN": {
    "GONDA BARU": ["JEJE", "MAFIA", "FARID", "FIKRI", "KASRIN", "ATI", "ZULL", "MULIADI", "RINDRA", "RUSLAN", "HAMIT"],
    "NGKARING-KARING": ["DIAS", "FATA", "ADEL", "KOLAM", "WAHID", "MERI", "RIAN", "LETTER", "NGURAH", "DAT", "SUAS", "CHELSIA", "TINI", "POLIS", "RIO"]
  },
  "IRVAN": {
    "PALABUSA, WANAJATI, KALIPU2, WONCO": [
      "ICAL (PALABUSA)",
      "AISA KLIPU2",
      "SAFIRMAN",
      "IBU NOVI",
      "ANDRI PALABUSA",
      "NENEK MARFAN",
      "YANA",
      "KADEK",
      "ALONG",
      "MOJI",
      "FAHRI KALIPU2",
      "MADING KALIPU2",
      "WAHYU"
    ]
  }
};

// BELUM_BAYAR: pelanggan yang belum transfer / status tanda tanya — dianggap WAJIB ZONK.
// isi: pelanggan yang belum transfer / tanda tanya — dianggap wajib ZONK.
const BELUM_BAYAR = {
  // "AGEN": {
  //   "AREA": ["NAMA", ...]
  // }
  "IRVAN": {
    "PALABUSA, WANAJATI, KALIPU2, WONCO": ["RESKY MOTOR"]
  }
};

const DATA_PESERTA = {
  "ALDIN": {
    "LIABUKU": [
      "ARCELO",
      "MERI",
      "NARA",
      "WALDI",
      "SAFIRA",
      "KAKSUARI",
      "ZELYA",
      "AKRAM",
      "RIO",
      "ALFIN",
      "RISMA",
      "PONDOK BAMBU",
      "DANI",
      "NOVRI",
      "BRYAN",
      "YAYU",
      "ELFRIDA",
      "ZEO",
      "PATIMURA",
      "LOLI",
      "ASRIADIN",
      "NIKMA",
      "ANCA",
      "ARUL",
      "HANS",
      "RISTO",
      "AMEL",
      "SILVANA",
      "YUSUF",
      "ANTON",
      "ALCELL",
      "NIRMALA",
      "SALSA",
      "PUTRI",
      "YUYUN",
      "SULTAN",
      "ARI",
      "MITA",
      "AYU",
      "INDIRA",
      "ALIF",
      "FADEL",
      "YOGA",
      "ADIT",
      "DIVA"
    ],
    "KOLESE": [
      "FANIZA",
      "REZA",
      "REVA",
      "ARYA",
      "NOVI",
      "MAHARUDDIN",
      "NURMIN",
      "ASYA",
      "LELY",
      "AQILA",
      "RIKO",
      "GISELLA",
      "MARWAN",
      "ILUN",
      "OCA",
      "RONI",
      "SYAFIQ",
      "PUTRI KOLESE",
      "PUTRI KALIA-LIA",
      "FERLI",
      "PUNCAK"
    ]
  },
  "MUNIR": {
    "KARYA BARU, BUGI, KAISABU": [
      "VEGA",
      "ICA",
      "WULANDARI",
      "PAK KAMALUDDIN",
      "PAK EDI",
      "DARMAWAN",
      "MULIADI",
      "RISWANDA",
      "FADIL",
      "ALFARIZY",
      "YAYAN",
      "IMA",
      "OKI",
      "ALTAR",
      "SALIADI",
      "AKBAR",
      "DAHLAN",
      "NURUL",
      "KARIM",
      "BAIM",
      "HASRAN",
      "DILA",
      "TITIN",
      "IBU IKA",
      "MARLINA",
      "FIRMAN",
      "AYURA",
      "SURADI",
      "WAHYU",
      "SATIA",
      "RIZKY",
      "RAHYUDIN",
      "KEPSEK SD 2 BUGI (SITIMARLINA)",
      "REHAN",
      "QNANA",
      "WIDYAWATI",
      "ASKA",
      "RISNU",
      "LA NAUJI",
      "LITA",
      "YUNIAR",
      "ANDRI",
      "YUYUN",
      "NINING",
      "BAGAS",
      "JUMAR",
      "SYAID",
      "AHMAD ( NASI GORENG )",
      "JMMART",
      "FATIR",
      "RANDI",
      "DITA",
      "YANI",
      "AGAM",
      "AQIM",
      "IZAN",
      "AQIL",
      "ZALFA",
      "UZLIA",
      "ZAFRAN",
      "ALI",
      "DEWA BUGI",
      "WANDA",
      "LISTIANA",
      "RAFLI",
      "SARMAN",
      "NURDIN",
      "SAFRIN",
      "YUSTI",
      "NURLAILA",
      "ALIUDIN",
      "YUSUF",
      "RAHMI",
      "NURHAYA",
      "HAJI",
      "MURSALIM",
      "SELFI",
      "FARID",
      "MAYANG",
      "AYU KAISABU",
      "ARUM",
      "SAFRI KAISABU",
      "WAHID",
      "OMA",
      "DEDE",
      "ERIK",
      "SALE",
      "RAHAYUNI",
      "LA GERTHA",
      "HARTATI",
      "SUCI",
      "FEBI",
      "ZANA",
      "ASMA",
      "FEGA",
      "LARAMA",
      "JELTI",
      "FIKA",
      "IVON",
      "MARIO",
      "RIRIN",
      "SHILA",
      "BAYU",
      "IIN",
      "ZUHUDIN",
      "TK",
      "RIKA",
      "HASNI",
      "HERI",
      "NURLINA",
      "WADESI",
      "RATU",
      "MURNI",
      "ARIN",
      "VENZO",
      "RIO",
      "MAHESA",
      "TONI",
      "LAJARUBI",
      "SUHAR",
      "ATIKA",
      "ZAKY",
      "DAFFA",
      "ARUN",
      "NADIA",
      "BULAN",
      "NISA",
      "ATI",
      "RISNO",
      "ARDIANSYAH",
      "ARUNIKA",
      "ILHAM",
      "KAOSA",
      "ANWAR",
      "YUSRIATI",
      "LA ASIRI",
      "HASNIA",
      "IDUL",
      "ADIFA",
      "NAILA",
      "RUSTINA",
      "NASIRA",
      "SUWARDIN"
    ],
    "WABOROBO": [
      "FATIR",
      "SILMA",
      "ISKANDAR",
      "UMA",
      "ARMIN",
      "AZIZAH",
      "AFFAN",
      "ALAN",
      "MIDUN",
      "ALIANG",
      "RIAN",
      "RENDRA",
      "ADI",
      "IDI",
      "SAIFUN",
      "NABILA",
      "LISA",
      "IREN",
      "ARDIN",
      "AGUS",
      "AYU",
      "TIWI",
      "AMEL",
      "BIO",
      "RENDI",
      "REHAN",
      "FIRA",
      "ELFI",
      "IWAN",
      "DUTA",
      "REFAN",
      "DINA",
      "RISA",
      "BILAL",
      "FENI",
      "SAUBI",
      "IQRA",
      "GUGUN",
      "JUNI",
      "NAFISA",
      "RAYAN",
      "RARA",
      "WULAN",
      "FANDA",
      "FANIZU",
      "UCOK",
      "PUSKEMAS",
      "DEWI",
      "RAHMAN",
      "SAWAL"
    ]
  },
  "NASRUN": {
    "GONDA BARU": [
      "AIRA",
      "DESI",
      "DIMAS 1",
      "DIMAS 2",
      "HAMZA",
      "IBU MARYAM",
      "INONG",
      "IPANG",
      "MAFIA",
      "MARNA",
      "PAK NURDIN",
      "UGO",
      "USER1 / DIAN",
      "USER 2 / YULAN",
      "WARUNG/ABIDIN",
      "YAMIN",
      "ZAKIR",
      "JLN MASUK SMK",
      "NAHLAN",
      "MULIADI",
      "ZULL",
      "JOKO",
      "SADAM",
      "FARIS",
      "JEMA",
      "ARSAT",
      "KARMIN",
      "AIRIN",
      "HALWA",
      "ABDUL",
      "DONI",
      "RIRIN",
      "HAMIT",
      "ARDI",
      "ILHAM",
      "ADINDA",
      "JEJE",
      "RUSLAN",
      "RINDRA",
      "ELVI",
      "ABDUL FELIX",
      "ALIMIN",
      "APANG",
      "INDIRA",
      "FERY",
      "YUNIAR",
      "IYAN",
      "AKMAL",
      "ELIS",
      "DIKA",
      "IKSAN",
      "AQIL",
      "KELUARGA",
      "KKIPAR",
      "FIKRI",
      "IRMA",
      "SALMA",
      "HAYRUN",
      "KASRIN",
      "ATI",
      "ALFATIR",
      "FARID",
      "NAILA",
      "JEFRI",
      "GURU SMK",
      "RENGKE GURU SMP 13",
      "AKILA",
      "FITA",
      "AIKA",
      "DENA",
      "PAK SAHRUN",
      "ALYA",
      "MOHAMT",
      "FIKI",
      "LUTFI",
      "DAWIA",
      "WIDYA",
      "YUSNI",
      "ZIOX",
      "WAHYU2",
      "SEKAR",
      "MEGA",
      "SIRAJUDIN",
      "GINO",
      "MAHIR",
      "ARA",
      "IKWAN",
      "KASMAN",
      "UNI",
      "YABIL",
      "YELSI"
    ],
    "NGKARING-KARING": [
      "USER2",
      "USER1/IBU LURAH",
      "USER 3 / KELAPA GADING",
      "PIPIN",
      "JONTOL",
      "BIO",
      "ITA",
      "SUKRI",
      "KEMBAR",
      "OKTA",
      "KESYA",
      "GALON",
      "YURIS",
      "DEKYU",
      "MEIRA",
      "KENZO",
      "ERLAND",
      "DIDIX",
      "DENIS",
      "DARMI",
      "NGURAH",
      "MERI",
      "MURNI",
      "RUKO",
      "DAT",
      "KEDIT",
      "MUKLIS",
      "RIAN",
      "ALESHA",
      "ADEL",
      "PAKGURU",
      "SUKADANA",
      "BUDI",
      "SURAYA",
      "KAU",
      "KOLAM",
      "SANTI",
      "CHELSIA",
      "POLIS",
      "RAFA",
      "ANGGA",
      "JIMI",
      "DEKSUMI",
      "INTAN",
      "SUAS",
      "AGUS",
      "TINI",
      "WIRA",
      "SURADIPA",
      "BOTAK",
      "PREEGO",
      "FATA",
      "DIAS",
      "WINDI",
      "MANGADI",
      "KETUTMUL",
      "RIO",
      "WAHID",
      "LETTER",
      "NOVA",
      "BLICING",
      "RANDY",
      "SUDIKSA",
      "KECAMATAN BUNGI",
      "TAUFIK",
      "AMEL",
      "ROS",
      "EGA",
      "SUDAR",
      "DANA",
      "DEWI",
      "SUCIPTA",
      "ESAA",
      "EVAN",
      "RENI",
      "SUKRENI",
      "GURENG",
      "DEVA",
      "YOGA",
      "NASWA",
      "KOLONON",
      "MASDIKA",
      "ARI",
      "YUSNA",
      "REDIASA",
      "HENDRA",
      "PIKUP",
      "GEDEPUTRA",
      "LINDA",
      "MERSI",
      "RESTI",
      "SUMANTARA",
      "KEN",
      "ASTRANADA",
      "DAYU",
      "ARIANA",
      "SUKANAYA",
      "ADITYA",
      "EKABENGKEL",
      "LAPERO",
      "MANTRI",
      "SUSILA",
      "KOMANGADI",
      "WULAN",
      "LARASWATI"
    ]
  },
  "IRVAN": {
    "PALABUSA, WANAJATI, KALIPU2, WONCO": [
      "HANAFI",
      "SARDIN",
      "AKILA",
      "YURANATA",
      "KENZIE/KIKI",
      "ARSILA",
      "PARMAN",
      "KARTINI",
      "DILAN",
      "PAK REY PUSKESMAS",
      "LAKSMANA",
      "IBU ANA",
      "IBU ANI",
      "ALIS",
      "PUTRA POLISI",
      "KAYUM",
      "FATIR",
      "PAK EMON",
      "TOMI 1",
      "TOMI 2",
      "IBU KARIATI",
      "FITRI WONCO",
      "DEWA TOGEL",
      "HAYAN",
      "REMBUN",
      "WANIPIRO",
      "NAHARUDIN",
      "PAK ONO",
      "PAK AWAL",
      "IBU BIDAN",
      "TOKO BONEK",
      "WAHYU",
      "MAMA ATI",
      "SARLIN",
      "ACO",
      "HARULI",
      "AMZIAH",
      "BPK SARI (PALABUSA)",
      "SURYA",
      "AGUS",
      "PAK EKA (WANAJATI)",
      "KOCED (WANAJATI)",
      "DITO PALABUSA",
      "FITRI/FITRA PALABUSA",
      "ICAL (PALABUSA)",
      "AISA KLIPU2",
      "ARTI",
      "ACHA KALIPU2",
      "BILAL KALIPU2",
      "PUTRI PALABUSA",
      "SAFIRMAN",
      "BPK BONARI",
      "AMRINA/KODIJA",
      "GALANG",
      "DITA",
      "ROMAN KALIPU2",
      "ERLANGGA",
      "BPK ARIF/IBU GURU",
      "HARIS KASIM",
      "JALUMA BASECAM",
      "MANGOLI WANAJATI",
      "IBU RESKY",
      "VILA DSA",
      "SHERIN KALIPU2",
      "MAMA AWAL",
      "SARLIA WONCO",
      "MAMA ROBY",
      "KELVIN KALIPU2",
      "VANESA PALABUSA",
      "PUTU WANAJATI",
      "AISYA",
      "ARDAT ON",
      "PAK YUSDI",
      "IBU REKSY",
      "EGI",
      "IBU NOVI",
      "TENDRI ABENG",
      "ELDIN",
      "TIKA",
      "BAHARI",
      "SIBA",
      "RESTI",
      "GUSTI",
      "IBU TONI",
      "FIRA",
      "RESKY MOTOR",
      "NARITA",
      "FINO",
      "FAISAL",
      "ANDRI PALABUSA",
      "GUSTI MAHENDRA",
      "LA ELI",
      "MAMA INAL PALABUSA",
      "GEDE WANAJATI",
      "MAMA ANGGI",
      "AFIF KALIPU2",
      "JALMAN",
      "NENEK MARFAN",
      "ASTIN PALABUSA",
      "SANTI",
      "YANA",
      "PAK POLISI RAYEN",
      "IBU ECI",
      "AYU ARINI",
      "ZUL",
      "DAFA",
      "KEPO",
      "JAMALIA/NAHIDA",
      "ALONG",
      "KASMA",
      "MOJI",
      "SATI",
      "WA MIRA",
      "PAK REY WARUNG",
      "FATRAH",
      "INAYA",
      "BENGKEL KALIPU2",
      "NARTI",
      "COMEL",
      "IFA",
      "JAMU",
      "DARMIN",
      "FIA KALIPU",
      "SUHAR ODE",
      "UDIN KALIPU2",
      "PERUSAHAAN MUTIARA",
      "FITRIANI EMPANG",
      "FAHRI KALIPU2",
      "MADING KALIPU2",
      "JULIANTO KALIPU2",
      "ANDRI EMPANG",
      "KANDANG AYAM POTONG",
      "SAWAL KALIPU2",
      "KADEK"
    ]
  }
};
